### ISSUE TITLE
[SETTINGS] FPS

### ISSUE THREAD

**Issue by crookm** [crookm/Asteroid#1]
The FPS should be configurable, with a minimum of 10, and a maximum of 30. It must not allow incorrect values such as out of bounds numbers or letters.

**Comment by crookm** [comment]
Fixed in commit [7aaf40a](https://github.com/crookm/Asteroid/commit/7aaf40a3bb89c952ffef8e7a8e73d8e03877bc97).

**Comment by BlackBrad** [comment]
Good job closing this.

**Comment by crookm** [comment]
Thank you Skrek.

**Comment by crookm** [comment]
FPS was not actually being set. Oops lol. Reopened.
